### ISSUE TITLE
Broke addon after update

### ISSUE THREAD

**Issue by F1T1L** [Vladinator/wow-addon-friendlistcolors#3]
Befor update same code:
[color=class][=accountName|name][if=characterName] ([=characterName])[/if][/color][if=noteText] [color=level][=noteText][/color][/if][if=notes] [color=level][=notes][/color][/if]

looks like:
  
![image](https://user-images.githubusercontent.com/32012911/192153852-966a3ec7-d720-4cd0-b32d-b41a7751db34.png)

code not working after update: 
![image](https://user-images.githubusercontent.com/32012911/192153864-20ff1114-fced-416b-a8f1-6d3154b8985d.png)

so now i use old vers.:

![image](https://user-images.githubusercontent.com/32012911/192153869-a9c2c7d4-1ee1-4557-a34b-8db5eefb0f89.png)

Plz fix it.

**Comment by F1T1L** [comment]
also add maybe profiles or layouts with good codes for friend list. will be nice :D

**Comment by F1T1L** [comment]
also code: [if=notes] [color=level][=notes][/color][/if]
do not apply color at offline ppls or who not in any game. 

![image](https://user-images.githubusercontent.com/32012911/192153809-33c31f6d-1074-48b0-abe2-d5abf48998f9.png)
looks more like porridge =)

**Comment by F1T1L** [comment]
also there 1 bugg.
![image](https://user-images.githubusercontent.com/32012911/192153958-c602fc8e-7055-4020-a2ad-9d4a2c06a1b0.png)

If i add  + at the end of string - code shows him self :D

**Comment by F1T1L** [comment]
also add a button like: SAVE or SAVE + RELOAD inside. because it's not obvious that you have to press Enter at the end of the line to save the code!! even these buttons do not help
![image](https://user-images.githubusercontent.com/32012911/192154290-1790f36a-eddd-40f7-b21c-e9d704cea13c.png)

**Comment by F1T1L** [comment]
also when i write code i cant even add paragraph /go next string so my code unreadable =(
in example looks fine. but i can write same way and turns out to be a messy mess 
![image](https://user-images.githubusercontent.com/32012911/192156575-dc72afd7-6398-4c94-b3c3-fcae58a31396.png)

**Comment by F1T1L** [comment]
also does not support multi line notes:
![image](https://user-images.githubusercontent.com/32012911/192155882-16f725d0-6138-44fb-8aa9-7b252eceeef9.png)

maybe it s good)

**Comment by F1T1L** [comment]
also if i delete code - i do not see field where i can write. its confuse =(
![image](https://user-images.githubusercontent.com/32012911/192155956-53a924ca-b46a-45e7-96cb-22435010f463.png)

one solution: template text like:"Write your code" if the field is empty.

**Comment by Vladinator** [comment]
Thanks a lot for so much testing, very useful information!

You wrote this almost same day as the update, then I did a couple extra updates where I fixed some bugs, that I suspect fixes some of the issues you mention, but not all of them as I just recently got time to read through what you wrote.

If you struggled to "reset" back to normal when you got into the empty format UI where the input box is not visible at all you can always reset the addon to the standard using `/run FriendListColorsDB=nil ReloadUI()` but hopefully you got it sorted since this was 10 days ago.

**Comment by F1T1L** [comment]
> Befor update same code: [color=class][=accountName|name][if=characterName] ([=characterName])[/if][/color][if=noteText] [color=level][=noteText][/color][/if][if=notes] [color=level][=notes][/color][/if]
> 
> looks like:
> 
> ![image](https://user-images.githubusercontent.com/32012911/192153852-966a3ec7-d720-4cd0-b32d-b41a7751db34.png)
> 
> code not working after update: ![image](https://user-images.githubusercontent.com/32012911/192153864-20ff1114-fced-416b-a8f1-6d3154b8985d.png)
> 
> so now i use old vers.:
> 
> ![image](https://user-images.githubusercontent.com/32012911/192153869-a9c2c7d4-1ee1-4557-a34b-8db5eefb0f89.png)
> 
> Plz fix it.

![image](https://user-images.githubusercontent.com/32012911/194168233-47ca498d-e2ba-481c-95a0-d342977b8dee.png)
![image](https://user-images.githubusercontent.com/32012911/194168310-1f8d367b-9ddf-4f0e-a5fd-76944a9a3be1.png)

Still not working.

**Comment by Vladinator** [comment]
Hello again, I looked at the syntax and there is a change, the old `noteText` is now called `notes`.

You can change your format to this instead:

    [color=class][=accountName|name][if=characterName] ([=characterName])[/if][/color][if=note|notes] [color=level][=note|notes][/color][/if]

I also combined both note texts into one (so it works for both BNet and WoW friends).

![image](https://user-images.githubusercontent.com/8304135/194631936-e258db1b-1537-49f7-b8fe-7da7fc5e7068.png)

**Comment by F1T1L** [comment]
> Hello again, I looked at the syntax and there is a change, the old `noteText` is now called `notes`.
> 
> You can change your format to this instead:
> 
> ```
> [color=class][=accountName|name][if=characterName] ([=characterName])[/if][/color][if=note|notes] [color=level][=note|notes][/color][/if]
> ```
> 
> I also combined both note texts into one (so it works for both BNet and WoW friends).
> 
> ![image](https://user-images.githubusercontent.com/8304135/194631936-e258db1b-1537-49f7-b8fe-7da7fc5e7068.png)

Okey. ty. works)
